### ISSUE TITLE
Reduce load time when loading the edit section for sites with large hierarchy

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/django-pagetree#63]
When running worth2 locally, the "view section" view loads in 500ms, while the "edit section" view loads in 2800ms. django-debug-toolbar reports the SQL queries only took 100ms. @sdreher says this due to the checks for locking / gating. It would be good to find a way to reduce the load time here.

**Comment by nikolas** [comment]
In addition to optimizing the checks for locking/gating (which I haven't looked into yet), integrating jquery-pjax in the pagetree admin view would definitely help here. With jquery-pjax, we could avoid having to render all 7 tabs at once, which shouldn't be necessary anyways.

**Comment by nikolas** [comment]
One performance issue is in displaying the hierarchy of pages (this loop in the template https://github.com/ccnmtl/django-pagetree/blob/master/pagetree/templates/pagetree/edit_page.html#L121)

Removing the `is_last_child` call reduces query and load time by about half. But we need this call in order to render the lists correctly. This function is being cached (https://github.com/ccnmtl/django-pagetree/blob/master/pagetree/models.py#L217) -- we could make sure the cache is behaving correctly.

The performance issue is bad on local development (i.e. my page load is 10 seconds on the WORTH2 pagetree edit view) but less noticeable on production, fortunately.

**Comment by thraxil** [comment]
Have you enabled Django's cache in your settings? I don't see a 'CACHES' line anywhere in the worth2 settings.

**Comment by nikolas** [comment]
closing this ticket because the load time for the pagetree admin section is now fine on worth2, after setting up caching.
